branch-defaults:
  main:
    environment: andrew-env
    group_suffix: null
environment-defaults:
  andrew-env:
    branch: null
    repository: null
global:
  application_name: test
  branch: null
  default_ec2_keyname: keypair-1
  default_platform: Python 3.8
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
